services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.local
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
    restart: always
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    restart: always