services:

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    restart: always

  server:
    depends_on:
      - cache
    build: 
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    restart: always

  cache:
    image: redis:6.2-alpine
    restart: always
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local